var content = {
    images: [
        '62fix01_o.jpg',
        'farewell_o.jpg',
        'porche_o.jpg',
        'girl_o.jpg',
        'pyramid_o.jpg',
        'hohohope_o.jpg',
        'rene_o.jpg',
        'ifLogo_o.jpg',
        'rhpAlbum_o.jpg',
        'allcity_o.jpg',
        'kid_o.jpg',
        'alley_o.jpg',
        'lain_o.jpg',
        'rocketship_o.jpg',
        'arm_o.jpg',
        'losAngeles_o.jpg',
        'saltonSea_o.jpg',
        'arron_o.jpg',
        'mWally01_o.jpg',
        'santaBarbara_o.jpg',
        'beckham_o.jpg',
        'mgAlbum_o.jpg',
        'sharaArron_o.jpg',
        'bike01_o.jpg',
        'mgFlier01_o.jpg',
        'station_o.jpg',
        'bike02_o.jpg',
        'mgNrAlbum_o.jpg',
        'subway_o.jpg',
        'bikeWeek_o.jpg',
        'moreGoodies_o.jpg',
        'taco_o.jpg',
        'borfo_o.jpg',
        'motorcycle_o.jpg',
        'tom_o.jpg',
        'brick01_o.jpg',
        'obama_o.jpg',
        'train_o.jpg',
        'building_o.jpg',
        'pierGTA_o.jpg',
        'trainyard_o.jpg',
        'buildings_o.jpg',
        'pierPC_o.jpg',
        'tunnel_o.jpg',
        'concertHall_o.jpg',
        'pierPressure_o.jpg',
        'unionStation_o.jpg',
        'downtown01_o.jpg',
        'pierReturn_o.jpg',
        'warehouse_o.jpg'
    ],
    imageLocation: 'images/portfolio/'
};

module.exports = content;
